config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]
  resources :comments, only: [:index, :create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :products
  resources :carts, only: :show

  # カード操作用
  post "/add_item", to: "carts#add_item"
  post "/update_item", to: "carts#update_item"
  delete "/delete_item", to: "carts#delete_item"

  # 商品並べ替え用
  get "products_sort", to: "products#sort", as: "products/sort"

  get "image_detail", to: "products#image_detail"

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  # devise_forより前にresourcesで指定すると、users/***の***がshowアクションの引数として識別されてしまう
  resources :users, only: [:index, :show]

  root to: "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_products, through: :favorites, source: 'product'
  has_many :carts, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # ページネーション用
  PER = 50

  def index
    @users = User.all.order(name: "ASC").page(params[:page]).per(PER)
  end

  def show
    @user = User.find(params[:id])
    @products = @user.products.all.order(name: "ASC").page(params[:page]).per(PER)
    @favorites = @user.favorite_products
    @orders = @user.orders
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/index.html.erb
<% provide(:title, " | ユーザー一覧") %>
<div class="contents-wrapper">
  <div class="container">
    <div class="row">
      <h1 class="text-center"><%= t('view.user') %>一覧</h1>
    </div>
    <% if !@users.blank? %>
      <div class="row">
        <% @users.each do |user| %>
          <div class="user-area">
            <div class="">
              <%= link_to "#{user.name}", user_path(user.id), class: "" %>
            </div>
          </div>
        <% end %>
        </div>
      <div class="row">
        <div class="paginate-area">
          <%= paginate @users %>
        </div>
      </div>
    <% else %>
      <div class="row">
        <p class="text-center">ユーザーがいません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, " | プロフィール") %>
<div class="contents-wrapper">
  <div class="container">
    <div class="row">
      <h2 class="text-center">プロフィール</h2>
      <div class="col-md-offset-1 col-md-3">
        <h3>顧客情報</h3>
        <div class="profile-area">
          <div class="field">
            名前：<%= @user.name %>
          </div>
          <div class="field">
            メールアドレス：<%= @user.email %>
          </div>
          <% if current_user?(@user) %>
            <p><%= link_to "カートの中身を見る", cart_path %></p>
            <p><%= link_to "プロフィール変更", edit_user_registration_path %></p>
            <% if current_user.admin? %>
              <p><a href="https://pay.jp/login" target="_blank">決済情報画面へ</a></p>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="container">
        <div class="col-md-8">
          <div class="row">
            <h3>登録<%= t('view.product') %></h3>
            <% if !@products.blank? %>
              <%= render @products %>
            <% elsif %>
              <p>登録商品がありません</P>
            <% end %>
          </div>
          <hr>
          <% if current_user?(@user) %>
            <div class="row">
              <h3><%= t('view.favorite') %></h3>
              <% if !@favorites.blank? %>
                <%= render @favorites %>
              <% elsif %>
                <p>お気に入りが登録されていません</P>
              <% end %>
            </div>
            <hr>
            <div class="row">
              <h3>注文履歴</h3>
              <% if !@orders.blank? %>
                <%= render @orders %>
              <% elsif %>
                <p>注文がありません</P>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>