config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]
  resources :comments, only: [:index, :create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :products
  resources :carts, only: :show

  # カード操作用
  post "/add_item", to: "carts#add_item"
  post "/update_item", to: "carts#update_item"
  delete "/delete_item", to: "carts#delete_item"

  # 商品並べ替え用
  get "products_sort", to: "products#sort", as: "products/sort"

  get "image_detail", to: "products#image_detail"

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  # devise_forより前にresourcesで指定すると、users/***の***がshowアクションの引数として識別されてしまう
  resources :users, only: [:index, :show]

  root to: "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item!, except: :show

  def show
    current_cart
    @cart_items = @cart.cart_items
  end

  def add_item
    if @cart_item.blank?
      @cart_item = @cart.cart_items.build(product_id: params[:product_id])
    end
    product = Product.find(params[:product_id])
    @cart_item.quantity += params[:quantity].to_i
    if @cart_item.save
      if product.update_stock(product.stock - params[:quantity].to_i)
        flash.now[:notice] = "カートに商品を追加しました"
        redirect_to cart_path(@cart.id), notice: "カートに商品を追加しました"
      end
    end
  end

  def update_item
    cart_item = CartItem.find(params[:cart_item_id])
    current_stock = cart_item.product.stock + cart_item.quantity
    if params[:quantity].to_i < current_stock
      if cart_item.product.update_stock(current_stock - params[:quantity].to_i) &&
         cart_item.update_quantity(params[:quantity])
          redirect_to cart_path(@cart.id), notice: "商品数を変更しました"
      end
    else
      redirect_to cart_path(@cart.id), notice: "商品数を変更できません。残数を確認してください。"
    end
  end

  def delete_item
    cart_item = CartItem.find(params[:cart_item_id])
    cart_item.product.update_stock(cart_item.product.stock + cart_item.quantity)
    cart_item.delete
    redirect_to cart_path(@cart.id), notice: "商品をカートから削除しました"
  end

  private

  def setup_cart_item!
    current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:product_id])
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<% provide(:title, " | ショッピングカート") %>
<div class="contents-wrapper">
  <div class="container">
    <h2 class="text-center">ショッピングカート</h2>
    <% if !@cart_items.blank? %>
      <div class="row">
        <p class="text-center">以下の商品がカートに追加されています</h2>
      <!-- <div class="col-md-offset-4 col-md-4"> -->
        <% @cart_items.each do |cart_item| %>
          <div class="cart-item-area">
            <p>商品名：<%= cart_item.product.name %></p>
            <p>価格：<%= cart_item.product.price %></p>
            <p>残数：<%= cart_item.product.stock %></p>
            <p>個数：<%= cart_item.quantity %></p>
            <div class="form-group">
              <%= form_tag(update_item_path, method: :post) do %>
                <%= hidden_field_tag :cart_item_id, cart_item.id %>
                <%= number_field_tag :quantity, nil, value: cart_item.quantity, min: 1, max: cart_item.product.stock + cart_item.quantity %>
                <%= submit_tag "再計算", class: "btn btn-primary" , :name => nil %>
              <% end %>
            </div>
            <% if cart_item.product.images? %>
              <p><%= image_tag cart_item.product.images[0].url %></p>
            <% else %>
              <p><%= image_tag "no_image.jpg", width:"200px", height:"200px", style:" border: 1px solid lightgray"%></p>
            <% end %>
            <p><%= link_to "カートから削除", delete_item_path(cart_item_id: cart_item.id), method: :delete %></p>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
          <%= link_to "購入画面へ", new_order_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="empty-cart">
          <p class="text-center">カートに商品がありません</h2>
        </div>
      </div>
    <% end %>
  </div>
</div>