config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]
  resources :comments, only: [:index, :create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :products
  resources :carts, only: :show

  # カード操作用
  post "/add_item", to: "carts#add_item"
  post "/update_item", to: "carts#update_item"
  delete "/delete_item", to: "carts#delete_item"

  # 商品並べ替え用
  get "products_sort", to: "products#sort", as: "products/sort"

  get "image_detail", to: "products#image_detail"

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  # devise_forより前にresourcesで指定すると、users/***の***がshowアクションの引数として識別されてしまう
  resources :users, only: [:index, :show]

  root to: "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: "user"
  has_many :cart_items, dependent: :destroy
  # 複数画像のアップロードに対応する mount_uploader⇒mount_uploaders
  mount_uploaders :images, PictureUploader

  # uniquenessにuser_idのスコープをつける（同一userでの一意制限）
  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :stock, presence: true, numericality: { only_integer: true }
  validates :price, presence: true, numericality: { only_integer: true }

  def update_stock(stock)
    update_attribute(:stock, stock)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  # ページネーション用
  PER = 10

  def index
    respond_to do |format|
      format.html do
        if !params[:search_name].blank? && !params[:search_date].blank? && params[:search_stock] == "1"
          session[:product_search_name] = params[:search_name]
          session[:product_search_date] = params[:search_date]
          session[:product_search_stock] = params[:search_stock]
          @products = Product.where("name LIKE ?", "%#{params[:search_name]}%")
                             .where(created_at: params[:search_date].in_time_zone.all_day)
                             .where.not(stock: 0)
                             .order(name: "ASC").page(params[:page]).per(PER)
        elsif !params[:search_name].blank?
          session[:product_search_name] = params[:search_name]
          if params[:search_stock] == "1"
            session[:product_search_stock] = params[:search_stock]
            @products = Product.where("name LIKE ?", "%#{params[:search_name]}%")
                               .where.not(stock: 0)
                               .order(name: "ASC").page(params[:page]).per(PER)
         else
            @products = Product.where("name LIKE ?", "%#{params[:search_name]}%")
                               .order(name: "ASC").page(params[:page]).per(PER)
         end
        elsif !params[:search_date].blank?
          session[:product_search_date] = params[:search_date]
          if params[:search_stock] == "1"
            session[:product_search_stock] = params[:search_stock]
            @products = Product.where(created_at: params[:search_date].in_time_zone.all_day)
                               .where.not(stock: 0)
                               .order(name: "ASC").page(params[:page]).per(PER)
          else
            @products = Product.where(created_at: params[:search_date].in_time_zone.all_day)
                               .order(name: "ASC").page(params[:page]).per(PER)
          end
        elsif params[:search_stock] == "1"
          session[:product_search_stock] = params[:search_stock]
          @products = Product.where.not(stock: 0).order(name: "ASC").page(params[:page]).per(PER)
        else
          session[:product_search_name] = nil
          session[:product_search_date] = nil
          session[:product_search_stock] = nil
          @products = Product.all.order(name: "ASC").page(params[:page]).per(PER)
        end
      end
      format.csv do
        if !params[:search_name].blank? && !params[:search_date].blank? && params[:search_stock] == "1"
          @products = Product.where("name LIKE ?", "%#{params[:product_search_name]}%")
                             .where(created_at: params[:product_search_date].in_time_zone.all_day)
                             .where.not(stock: 0)
                             .order(name: "ASC").page(params[:page]).per(PER)
        elsif !session[:product_search_name].blank?
          if params[:product_search_stock] == "1"
            @products = Product.where("name LIKE ?", "%#{params[:product_search_name]}%")
                               .where.not(stock: 0)
                               .order(name: "ASC").page(params[:page]).per(PER)
          else
            @products = Product.where("name LIKE ?", "%#{session[:product_search_name]}%")
                               .order(name: "ASC").page(params[:page]).per(PER)
          end
        elsif !session[:product_search_date].blank?
          if params[:product_search_stock] == "1"
            @products = Product.where(created_at: params[:product_search_date].in_time_zone.all_day)
                               .where.not(stock: 0)
                               .order(name: "ASC").page(params[:page]).per(PER)
          else
            @products = Product.where(created_at: params[:product_search_date].in_time_zone.all_day)
                               .order(name: "ASC").page(params[:page]).per(PER)
          end
        elsif session[:product_search_stock] == "1"
          @products = Product.where.not(stock: 0)
                             .order(name: "ASC").page(params[:page]).per(PER)
        else
          @products = Product.all.order(name: "ASC").page(params[:page]).per(PER)
        end
        send_data render_to_string, filename: "products.csv", type: :csv
#        products_csv
      end
    end
  end


  def show
    @product = Product.find(params[:id])
    @comment = Comment.new
    @comments = @product.comments
    @recommends = Product.where(category_id: @product.category_id)
                         .where.not(user_id: current_user.id)
                         .where.not(id: @product.id)
                         .order("RAND()").limit(5)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = params[:user_id]
    # @product.user = current_user
    if @product.save
      redirect_to products_path, notice: "商品を登録しました"
    else
      render :new, danger: "商品登録に失敗しました"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.user == current_user
      if @product.update_attributes(product_params)
        redirect_to product_path, notice: "商品情報を変更しました"
      else
        render "new", danger: "商品情報の変更に失敗しました"
      end
    else
      redirect_to products_path
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path, notice: "商品を削除しました"
  end

  def sort
    case params[:sort_condition]
    when "1" then
      @products = Product.all.order(name: "ASC").page(params[:page]).per(PER)
    when "2" then
      @products = Product.all.order(user_id: "ASC").page(params[:page]).per(PER)
    when "3" then
      @products = Product.all.order(price: "ASC").page(params[:page]).per(PER)
    end
    render :index
  end

  def image_detail
    @product = Product.find(params[:product_id])
    @image = @product.images[params[:index].to_i]
    respond_to do |format|
      format.js
    end
  end


  private

    def product_params
      # 複数画像を受け取るように対応 :image⇒{image: []}
      params.require(:product).permit(:name, {images: []}, :description, :category_id, :stock, :price)
    end

    # def products_csv
    #   csv_date = CSV.generate do |csv|
    #     csv_column_names = ["商品名","説明","登録者","登録日"]
    #     csv << csv_column_names
    #     @products.each do |product|
    #       csv_column_values = [
    #         product.name,
    #         product.description,
    #         product.user.name,
    #         product.created_at,
    #       ]
    #       csv << csv_column_values
    #     end
    #   end
    #   send_data(csv_date,filename: "product.csv")
    # end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_image_detail.html.erb
<div class="modal-dialog">
  <%= image_tag @image.url, class: "center-block", style: "width:75%" %>
</div>

app/views/products/_product.html.erb
<div class="product-area-short">
  <div class="field">
    商品名：<%= link_to "#{product.name}", product_path(product.id) %>
  </div>
  <div class="field">
    販売者：<%= link_to "#{product.user.name}", user_path(product.user.id) %>
  </div>
  <% if product.images? %>
    <%= image_tag product.images[0].url %>
  <% else %>
    <%= image_tag "no_image.jpg", width:"200px", height:"200px", style:" border: 1px solid lightgray"%>
  <% end %>
</div>

app/views/products/edit.html.erb
<% provide(:title, " | 商品情報変更") %>
<div class="contents-wrapper">
  <div class="container">
    <div class="row">
        <h2 class="text-center">商品情報変更</h2>
      <div class="col-md-offset-4 col-md-4">
        <%= form_for @product do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :category %>
            <%= f.collection_select :category_id, Category.all, :id, :name %>
          </div>

          <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, min: 1, max:999999, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :stock %>
            <%= f.number_field :stock, min: 1, max: 99, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: "form-control" %>
          </div>

          <div class="form-group">
          <%= f.label :images %>
          <% if @product.images? %>
            <% @product.images.each do |image| %>
              <p><%= image_tag image.url %></p>
            <% end %>
          <% else %>
            <p><%= image_tag "no_image.jpg", width:"200px", height:"200px", style:" border: 1px solid lightgray"%></p>
          <% end %>
          <%= f.file_field :images, multiple: true %>
          </div>

          <%= f.submit "変更", class: "form-control btn-primary btn-block" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/image_detail.js.erb
$("#image_detail").html("<%= escape_javascript(render 'image_detail') %>");
$("#image_detail").modal("show");

app/views/products/index.html.erb
<% provide(:title, " | 商品一覧") %>
<div class="contents-wrapper">
  <div class="container">
    <h1 class="text-center"><%= t('view.product') %>一覧</h1>
    <% if !@products.blank? %>
      <div class="row">
        <div class="col-md-offset-4 col-md-4">
        <%= form_tag(products_path, method: :get) do %>
          <div class="form-group">
            <p>商品名：<%= text_field_tag :search_name %></p>
            <p>登録日：<%= date_field_tag :search_date %></p>
            <%= label_tag :search_stock, "在庫ありのみ" %>
            <%= check_box_tag :search_stock %>
          </div>
          <%= submit_tag "検索", class: "center-block btn btn-primary" , :name => nil %>
        <% end %>
        </div>
      </div>
      <hr/>
      <div class="row">
        <div class="sort-title">
          並べ替え：
        </div>
        <div>
          <%= form_tag(products_sort_path, method: :get) do  %>
            <%= select_tag 'sort_condition', options_for_select([["名前","1"], ["販売者","2"], ["価格","3"]]) %>
            <%= submit_tag "並べ替え", class: "btn btn-primary", :name => nil %>
          <% end %>
        </div>
      </div>
      <hr/>
      <div class="row">
        <div class="paginate-area">
          <%= paginate @products %>
        </div>
      </div>
      <div class="row center-block">
        <% @products.each do |product| %>
          <div class="product-area">
            <p>商品名：<%= link_to "#{product.name}", product_path(product.id) %></p>
            <p>販売者：<%= link_to "#{product.user.name}", user_path(product.user.id) %></p>
            <p>価格：<%= product.price %></p>
            <% if product.stock != 0 %>
              <p>残数：<%= product.stock %></p>
            <% else %>
              <p style="color:red">現在販売されていません。</p>
            <% end %>
            <% if product.images? %>
              <p><%= image_tag product.images[0].url %></p>
            <% else %>
              <p><%= image_tag "no_image.jpg", width:"200px", height:"200px", style:" border: 1px solid lightgray"%></p>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div class="paginate-area">
          <%= paginate @products %>
        </div>
      </div>
      <hr/>
      <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
            <%= link_to "CSV形式で商品一覧をダウンロード", products_path(format: :csv), class: "btn btn-primary" %>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="empty-product">
          <p class="text-center">商品がありません</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<% provide(:title, " | 商品登録") %>
<div class="contents-wrapper">
  <div class="container">
    <div class="row">
      <h2 class="text-center"><%= t("view.product") %>登録</h2>
      <div class="col-md-offset-4 col-md-4">
        <%= form_for @product do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <%= hidden_field_tag :user_id, current_user.id %>

          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :category %>
            <%= f.collection_select :category_id, Category.all, :id, :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, min: 1, max:999999, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :stock %>
            <%= f.number_field :stock, min: 1, max: 99, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: "form-control" %>
          </div>

          <div class="form-group">
          <%= f.label :images %>
          <!-- <%= f.file_field :image %> -->
          <%= f.file_field :images, multiple: true %>
          <p>*この写真がメイン写真になります</P>
          <%= f.file_field :images, multiple: true %>
          <%= f.file_field :images, multiple: true %>
          </div>

          <%= f.submit "登録", class: "form-control btn-primary btn-block" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<% provide(:title, " | 商品詳細") %>
<div class="contents-wrapper">
  <div class="container">
    <div class="row">
      <h2 class="text-center"><%= t('view.product') %>詳細</h2>
      <% if @product.stock <= 0 %>
        <h4 class="text-center" style="color:red;font-weight:bold">この商品は現在在庫がないためご購入いただけません</h4>
      <% end %>
      <div class="col-md-offset-1 col-md-3">
        <div class="profile-area">
          <h3><%= t('view.product') %>情報</h3>
          <p>商品名：<%= @product.name %></p>
          <p>商品説明：<%= @product.description %></p>
          <p>価格：<%= @product.price %></p>
          <p>在庫：<%= @product.stock %></p>
          <% if @product.images? %>
            <!-- javascript側へproduct.imagesの配列長さを渡すために設置 -->
            <%= hidden_field_tag :product_images_length, @product.images.length %>
            <p id="main-image"><%= image_tag @product.images[0].url %></p>
            <div class="field">
              <% @product.images.each_with_index do |image, n| %>
                <!-- <%= image_tag image.url, style: "width:50px;height:50px;" , id: "sub-image-#{n}"%> -->
                <%= link_to image_detail_path(index: n, product_id: @product.id), remote: true do %>
                  <%= image_tag image.url, style: "width:50px;height:50px;" , id: "sub-image-#{n}"%>
                <% end %>
              <% end %>
            </div>
          <% else %>
            <p><%= image_tag "no_image.jpg", width:"200px", height:"200px", style:" border: 1px solid lightgray"%></p>
          <% end %>
          <% if current_user?(@product.user) %>
            <p><%= link_to "商品情報変更", edit_product_path %></p>
            <p><%= link_to "商品削除", product_path, method: :delete %></p>
          <% else %>
            <% if @product.stock > 0 %>
              <!-- <p><%= link_to "商品購入", new_order_path(product_id: @product.id) %></p> -->
              <div class="form-group">
                <%= form_tag(add_item_path, method: :post) do %>
                  <%= hidden_field_tag :product_id, @product.id %>
                  <!-- nilを入れることでvalueを空にする -->
                  <%= number_field_tag :quantity, nil, value: 1, min: 1, max: @product.stock %>
                  <%= submit_tag "カートに入れる", class: "btn btn-primary" , :name => nil %>
                <% end %>
              </div>
            <% end %>
            <% if !@product.favorite_users.include?(current_user) %>
            <!-- product_idという名前のparamにproductのidをセットしてアクションへ渡す -->
              <%= link_to favorites_path(product_id: @product.id), method: :post do %>
                <p><i class="far fa-star fa-2x"></i></p>
              <% end %>
            <% else %>
              <%= link_to favorite_path, method: :delete do %>
                <i class="fas fa-star fa-2x"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="commnet-area">
          <h3><%= t('view.comment') %>一覧</h3>
          <div id="comment">
            <%= render "comments/comment" %>
          </div>
          <%= form_for @comment, remote: true do |f| %>
            <%= hidden_field_tag :product_id, @product.id %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <div class="form-group" id>
              <%= f.label :コメントする %>
              <%= f.text_area :comment, class: "form-control" %>
            </div>
            <%= f.submit "コメント投稿", class: "form-control btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-3">
        <h3><%= t('view.recommend') %></h3>
        <% if !@recommends.blank? %>
          <%= render @recommends %>
        <% elsif %>
          <p>おすすめがありません</P>
        <% end %>
      </div>
      <div id="image_detail" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    </div>
  </div>
</div>
<!-- <script type="text/javascript">
  var main_image  = document.getElementById("main-image");
  var product_images_length = document.getElementById("product_images_length");
  for (var i = 0; i < product_images_length.value; i++) {
    eval("sub_image_" + i + "=" + "document.getElementById('sub-image-" + i + "')" + ";");
  }
  sub_image_0.addEventListener("click", function() {
    main_image.innerHTML = "<%= escape_javascript(image_tag @product.images[0].url) if !@product.images[0].blank? %>";
  });
  sub_image_1.addEventListener("click", function() {
    main_image.innerHTML = "<%= escape_javascript(image_tag @product.images[1].url) if !@product.images[1].blank? %>";
  });
  sub_image_2.addEventListener("click", function() {
    main_image.innerHTML = "<%= escape_javascript(image_tag @product.images[2].url) if !@product.images[2].blank? %>";
  });
</script> -->