config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]
  resources :comments, only: [:index, :create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :products
  resources :carts, only: :show

  # カード操作用
  post "/add_item", to: "carts#add_item"
  post "/update_item", to: "carts#update_item"
  delete "/delete_item", to: "carts#delete_item"

  # 商品並べ替え用
  get "products_sort", to: "products#sort", as: "products/sort"

  get "image_detail", to: "products#image_detail"

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
  # devise_forより前にresourcesで指定すると、users/***の***がshowアクションの引数として識別されてしまう
  resources :users, only: [:index, :show]

  root to: "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  validates :cart_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true }

  def update_quantity(quantity)
    update_attribute(:quantity, quantity)
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :product_id, presence: true
  validates :user_id, presence: true
  validates :comment, presence: true, length: {maximum: 100}

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :carts, dependent: :destroy

  validates :user_id, presence: true
  validates :total_price, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: "user"
  has_many :cart_items, dependent: :destroy
  # 複数画像のアップロードに対応する mount_uploader⇒mount_uploaders
  mount_uploaders :images, PictureUploader

  # uniquenessにuser_idのスコープをつける（同一userでの一意制限）
  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :stock, presence: true, numericality: { only_integer: true }
  validates :price, presence: true, numericality: { only_integer: true }

  def update_stock(stock)
    update_attribute(:stock, stock)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_products, through: :favorites, source: 'product'
  has_many :carts, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item!, except: :show

  def show
    current_cart
    @cart_items = @cart.cart_items
  end

  def add_item
    if @cart_item.blank?
      @cart_item = @cart.cart_items.build(product_id: params[:product_id])
    end
    product = Product.find(params[:product_id])
    @cart_item.quantity += params[:quantity].to_i
    if @cart_item.save
      if product.update_stock(product.stock - params[:quantity].to_i)
        flash.now[:notice] = "カートに商品を追加しました"
        redirect_to cart_path(@cart.id), notice: "カートに商品を追加しました"
      end
    end
  end

  def update_item
    cart_item = CartItem.find(params[:cart_item_id])
    current_stock = cart_item.product.stock + cart_item.quantity
    if params[:quantity].to_i < current_stock
      if cart_item.product.update_stock(current_stock - params[:quantity].to_i) &&
         cart_item.update_quantity(params[:quantity])
          redirect_to cart_path(@cart.id), notice: "商品数を変更しました"
      end
    else
      redirect_to cart_path(@cart.id), notice: "商品数を変更できません。残数を確認してください。"
    end
  end

  def delete_item
    cart_item = CartItem.find(params[:cart_item_id])
    cart_item.product.update_stock(cart_item.product.stock + cart_item.quantity)
    cart_item.delete
    redirect_to cart_path(@cart.id), notice: "商品をカートから削除しました"
  end

  private

  def setup_cart_item!
    current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:product_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # ページネーション用
  PER = 50

  def index
    @users = User.all.order(name: "ASC").page(params[:page]).per(PER)
  end

  def show
    @user = User.find(params[:id])
    @products = @user.products.all.order(name: "ASC").page(params[:page]).per(PER)
    @favorites = @user.favorite_products
    @orders = @user.orders
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
      # 注文済カートの場合は新しいカートを作成
      if !@cart.order_id.blank?
        @cart = Cart.create(user_id: current_user.id)
        session[:cart_id] = @cart.id
      end
    else
      # where句で検索する場合、結果が1件でも複数件として扱われるため、firstで強制的に1件にする
      @cart = Cart.where(user_id: current_user.id).where(order_id: nil).first
      if @cart.blank?
        @cart = Cart.create(user_id: current_user.id)
        session[:cart_id] = @cart.id
      end
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
  <ul>
    <li><%= link_to '会社概要' %></li>
    <li><a href="mailto:terunrun@gmail.com" target="_blank">コンタクト</a></li>
    <li><a href="#top">一番上へ戻る</a></li>
  </ul>
  <p>&copy; SFF</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
  <!-- <div class="container"> -->
  <div class="navbar-header">
    <div class="navbar-brand">
      <%= link_to root_path do %>
        SFF Online
      <% end %>
    </div>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <% if user_signed_in? %>
      <p class="text-center"><%= t('view.welcome', name: current_user.name) %><p>
    <% end %>
  </div>
  <div id="gnavi" class="collapse navbar-collapse">
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '商品一覧', products_path %></li>
        <li><%= link_to '商品登録', new_product_path %></li>
        <li><%= link_to 'カート', cart_path(current_user.id) %></li>
        <li><%= link_to 'プロフィール', user_path(current_user.id) %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '新規登録', new_user_registration_path %></li>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
      </ul>
    <% end %>
  </div>
  <% if !notice.blank? %>
    <p id="flash" class="notice text-center"><%= notice %></p>
  <% elsif !alert.blank? %>
    <p id="flash" class="alert text-center"><%= alert %></p>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sff <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- fontawesomeを使用 -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Swiperを使用-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.7/css/swiper.min.css" />
  </head>
  <body>
    <header>
      <%= render "layouts/header" %>
    </header>

    <%= yield %>

    <footer>
      <%= render "layouts/footer" %>
    </footer>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Swiperを使用-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.7/js/swiper.min.js"></script>
    <script>
      $(function(){
        $("#flash").fadeOut(3000);
      });

      window.addEventListener('DOMContentLoaded', function() {
        var mySwiper = new Swiper ('.static-pages-wrapper .swiper-container', {
          loop: true, // 最後のスライドまで到達した場合、最初に戻らずに続けてスライド可能にするか。
          speed: 1000, // スライドが切り替わるトランジション時間(ミリ秒)。
          slidesPerView: 1, // 何枚のスライドを表示するか
          spaceBetween: 0, // スライド間の余白サイズ(ピクセル)
          direction: 'vertical', // スライド方向。 'horizontal'(水平) か 'vertical'(垂直)。effectオプションが 'slide' 以外は無効。
          effect: 'slide', // "slide", "fade"(フェード), "cube"(キューブ回転), "coverflow"(カバーフロー) または "flip"(平面回転)

          // スライダーの自動再生
          // autoplay: true 　のみなら既定値での自動再生
          autoplay: {
            delay: 3000, // スライドが切り替わるまでの表示時間(ミリ秒)
            stopOnLast: false, // 最後のスライドまで表示されたら自動再生を中止するか
            disableOnInteraction: true // ユーザーのスワイプ操作を検出したら自動再生を中止するか
          },

          // レスポンシブ化条件
          breakpoints: {
            // 980ピクセル幅以下になったら
            980: {
              slidesPerView: 1,
              spaceBetween: 0
            },
            // 640ピクセル幅以下になったら
            640: {
              slidesPerView: 1,
              spaceBetween: 0
            }
          },

          // ページネーションを表示する場合
          pagination: {
            el: '.swiper-pagination',　 // ページネーションを表示するセレクタ
            clickable: true
          },

          // 前後スライドへのナビゲーションを表示する場合
          // navigation: {
          //   nextEl: '.swiper-button-next', // 次のスライドボタンのセレクタ
          //   prevEl: '.swiper-button-prev', // 前のスライドボタンのセレクタ
          // },

          // スクロールバーを表示する場合
          // scrollbar: {
          //   el: '.swiper-scrollbar', // スクロールバーを表示するセレクタ
          // }
        });
      }, false);
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<div Class="static-pages-wrapper">
  <div class="swiper-container">
    <!-- 全スライドをまとめるラッパー -->
    <div class="swiper-wrapper">
      <!-- 各スライド -->
      <div class="swiper-slide">
        <div class="image-container-1">
          <p class="text-center">あなたの作ったあんなものやこんなものを売ったり</p>
        </div>
      </div>
      <div class="swiper-slide">
        <div class="image-container-2">
          <p class="text-center">誰かが作ったあんなものやこんなものを買ったり</p>
        </div>
      </div>
      <div class="swiper-slide">
        <div class="image-container-3">
          <p class="text-center">さあ今すぐ始めよう</p>
        </div>
      </div>
    </div>

    <!-- ページネーションを表示する場合 -->
    <div class="swiper-pagination"></div>

    <!--
    前後スライドへのナビゲーションボタン(矢印)を表示する場合
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    -->

    <!--
    スクロールバーを表示する場合
    <div class="swiper-scrollbar"></div>
    -->

  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <!-- エラーメッセージの数を表示 -->
      入力内容に<%= object.errors.count %>個のエラーがあります。
    </div>
    <ul>
      <!-- エラーメッセージを表示 -->
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    <ul>
  </div>
<% end %>